### ISSUE TITLE
Invalid state ref when open the home page.

### ISSUE THREAD

**Issue by anderson-rocha** [start-angular/sb-admin-angular#37]
This message is showing in browser console when it is open.

Error: Invalid state ref ''
    at B (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.min.js:7:23780)
    at D.link (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.min.js:7:24122)
    at J (http://localhost:9000/bower_components/angular/angular.min.js:53:345)
    at f (http://localhost:9000/bower_components/angular/angular.min.js:46:399)
    at J (http://localhost:9000/bower_components/angular/angular.min.js:53:286)
    at f (http://localhost:9000/bower_components/angular/angular.min.js:46:399)
    at J (http://localhost:9000/bower_components/angular/angular.min.js:53:286)
    at http://localhost:9000/bower_components/angular/angular.min.js:59:454
    at http://localhost:9000/bower_components/angular/angular.min.js:70:515
    at u (http://localhost:9000/bower_components/angular/angular.min.js:97:280) <a ui-sref="{{goto}}">

**Comment by MileanCo** [comment]
How did you fix this? I have the same problem.

**Comment by anderson-rocha** [comment]
In app/scripts/directives/dashboard/stats/stats.html I modified the <a
ui-sref="{{goto}}"> to <a href="#">.

Att.

Anderson Rocha.
Cel 18 9 9666 0338

2015-10-13 16:33 GMT-03:00 Joel Stenkvist notifications@github.com:

**Comment by MileanCo** [comment]
Thank you! My problem was actually related to that NPM put my "bower_components" inside "./client/bower_components" instead of just "./bower_components" . Silly but moving the components out fixed it.

Joel
